#include<stdio.h>
#include<parser.h>
#include<lexer.h>

int main(){
	printf("Welcome\n");
	while(1){
		printf("Enter any option: ");
    	printf("0: For exit.\n");
    	printf("1: For removal of comments\n");
    	printf("2: For print the token list generated by lexer\n");
    	printf("3: For removal of comments\n");
    	printf("4: Total Time Taken for the lexer and parser to verify syntactic correctness\n");
    	int option;
		scanf("%d",&option); 
		if(option==0){
			printf("Exiting");
			break;
		}	
		switch(option){
			case 1:{
				printf("Please Enter the name of the Testfile: ");
				char testcaseFile[50];
				scanf("%s",testcaseFile);
				removeComments(char *testcaseFile);
					
			}
			case 2:{
				printf("Please Enter the name of the Testfile: ");
				char testcaseFile[50];
				scanf("%s",testcaseFile);
				removeComments(char *testcaseFile);

			}
			case 3:
			case 4:
			default:{
				printf("Invalid Option: Please try again\n");
			}
		}
    }


}