/* 			GROUP NO : 18
	NIKHIL DEVABHAKTUNI    	2017A7PS0032P
	YAGANTI SHIVA KRISHNA  	2017A7PS0045P
	SANKEERTH NALAM	       	2017A7PS0070P
	PAIDIPALLY HEMANTH RAO 	2017A7PS0159P 
						*/

#include<stdio.h>
#include<parser.h>
#include<lexer.h>

int main(int argc,char *argv[]){
	printf("Welcome\n");
	while(1){
		printf("Enter any option: ");
    	printf("0: For exit.\n");
    	printf("1: For removal of comments\n");
    	printf("2: For print the token list generated by lexer\n");
    	printf("3: For removal of comments\n");
    	printf("4: Total Time Taken for the lexer and parser to verify syntactic correctness\n");
    	int option;
		scanf("%d",&option); 
		if(option==0){
			printf("Exiting");
			break;
		}	
		switch(option){
			case 1:{
				//printf("Please Enter the name of the Testfile: ");
				//char testcaseFile[50];
				//scanf("%s",testcaseFile);
				removeComments(argv[1]);
					
			}
			case 2:{
				//printf("Please Enter the name of the Testfile: ");
				//char testcaseFile[50];
				//scanf("%s",testcaseFile);

				intialize_symbol_table();

				struct tokenlexemepair* ex;
				FILE* fp=fopen(argv[1],"r");
				if(fp==NULL)printf("NULL file given\n");

				while(1){
					fp=getStream(fp);

					while(1){
						ex=getNexttoken(stream);
						if(streamover==true) break;
						if(iserror==true)continue;
						printf("%-3d %-21s %-18ss\n",line_no,ex->lexeme,ex->token);
					}
					
					if(fileover==true) break;
				}

			}
			case 3:{
				intialize_symbol_table();
				int firstset[57][150];
				int followset[57][1024];
				ComputeFirstAndFollowSets(gr,firstset,followset);
				int parse_table[115][115]={-1};
				memset(parse_table,-1,sizeof(parse_table));
				createParseTable(firstset,followset,parse_table);
				FILE* fp=fopen("parse_table_1.txt","w");
				for(int i=1;i<57;i++){
					for(int j=57;j<114;j++){
						fprintf(fp,"%d(%d)   ",parse_table[i][j],j);
					}
					fprintf(fp,"%d(0)\n",parse_table[i][0]);
				}
				struct node * root=parseInputSourceCode("test",parse_table);

			}
			case 4:{


			}
			default:{
				printf("\033[1;31m");
				printf("Invalid Option: Please try again\n");
  			    printf("\033[0m");

			}
		}
    }


}
