#include<stdio.h>
#include<parser.h>
#include<lexer.h>

int main(){
	printf("Welcome\n");
	while(1){
		printf("Enter any option: ");
    	printf("0: For exit.\n");
    	printf("1: For removal of comments\n");
    	printf("2: For printing the token list generated by lexer\n");
    	printf("3: For printing all lexival and syntactic errors and the parse tree\n");
    	printf("4: Total Time Taken for the lexer and parser to verify syntactic correctness\n");
    	int option;
		scanf("%d",&option); 
		if(option==0){
			printf("Exiting");
			break;
		}	
		switch(option){
			case 1:
				printf("Please Enter the name of the Testfile: ");
				char testcaseFile[50];
				scanf("%s",testcaseFile);
				removeComments(char *testcaseFile);
				break;
					
			case 2:
				printf("Please Enter the name of the Testfile: ");
				char testcaseFile[50];
				scanf("%s",testcaseFile);
				// invoke only lexer and print each token for a line with line number
	 			//format: line_no    lexeme     Token_name
				// lexical error with lexemes and line number

			case 3:
				//invokes both lexer and parser 
				//prints both lexical and syntactic errors linewise
				//prints parse tree
			case 4:
				//For printing (on the console) the total time taken by your stage 1 code of lexer and parser to verify the syntactic correctness
			default:{
				printf("Invalid Option: Please try again\n");
			}
		}
    }


}
